# don't build tags, it's redundant
if: tag IS blank

language: node_js

node_js:
  - "11"
  - "10"
  - "8"

os:
  - linux
  - windows

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

matrix:
  fast_finish: true
  exclude:
    # only run windows CI on LTS (v10)
    - node_js: "11"
      os: windows
    - node_js: "8"
      os: windows

cache: npm

before_install:
  - if [[ "$(npm -v)" != "$(npm v npm dist-tags.latest)" ]]; then npm i -g npm@latest; fi

install: npm ci

script:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then npm run lint; fi
  - npm run build
